// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/26/2026, 7:23:37 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/szl/Desktop/26Spring/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/plugins/**/*.{js,ts,mjs}","/Users/szl/Desktop/26Spring/blog/composables/**/*.{js,ts,mjs}","/Users/szl/Desktop/26Spring/blog/utils/**/*.{js,ts,mjs}","/Users/szl/Desktop/26Spring/blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/szl/Desktop/26Spring/blog/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["11"] = "/Users/szl/Desktop/26Spring/blog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;